// Main testbench: the whole CPU + PIC + mtimer system under one self-checking
// run.
//
// Setup (a small SoC):
// - cpu_top, imem model @ 0x0000 on the ibus
// - dbus through two address decoders: the 0x3000_0000 window splits into the
//   real pic (0x3000_0000) and the real mtimer (0x3001_0000); everything else
//   goes to the dmem model @ 0x2000 (DECERR out of its range)
// - passive AXI protocol monitors on ibus, dbus, the PIC and mtimer ports
// - the TB plays the peripherals on irq_src[6:0] the way the DMA/DP-SRAM would
//   (raise on event, hold until "cleared"); channel 7 is the real mtimer irq
//
// program_axi.s exercises every ISA group, every sync trap cause, the CSR rules
// and the PIC registers; results land in registers and a dmem scoreboard,
// checked after the end marker (x23 = 0x123). Invariants are sampled every cycle
// (ack shape, PIC consistency), and monitor error counters must end at 0.
//
// Interrupt choreography (why each source moves the way it does):
// - src5 rises after reset and stays up: enabled in the PIC but never in mie, so
//   it must never be taken (no ack[5]), which proves the two masks are independent
// - src2 + src3 rise together once MIE is set: ch2 served first (priority), ch3
//   right after ch2's MRET; src3 stays high through its handler, so the
//   in-service mask keeps it out of cpu_irq (suppression) and it's taken once
// - src2 rises again while a data-bus read is in flight: the ack may only come
//   after the R beat: held through the stall, taken at the boundary, load intact

// label addresses, generated by asm.py next to program_axi.hex, so a code
// change that shifts a label updates the checks automatically (see +incdir)
`include "program_axi_sym.vh"
// SoC base addresses in one place
`include "soc_map.vh"

// AXI4-Lite wiring macros, shared with tb_dual_core
`include "axi_lite_macros.vh"

module tb_cpu_axi;

wire clk, rst_n;

ck_rst_tb #(.CK_SEMIPERIOD(5)) ck_rst_inst (
    .clk   (clk),
    .rst_n (rst_n)
);

// DUT bus bundles: ib = ibus (read-only), db = dbus; after the dbus decoder
// d0 = dmem leg, p = peripheral leg; after the peripheral decoder pp = PIC,
// t = mtimer
`AXIL_RD_WIRES(ib);
`AXIL_WIRES(db);
`AXIL_WIRES(d0);
`AXIL_WIRES(p);
`AXIL_WIRES(pp);
`AXIL_WIRES(t);

wire [7:0]  cpu_irq;
wire [2:0]  cpu_irq_id;
wire [7:0]  cpu_irq_ack;
wire        cpu_in_trap;
reg  [7:0]  irq_src;        // peripheral lines into the PIC (DMA/SRAM stand-in)
wire        tmr_irq;

cpu_top #(.RESET_PC(`IMEM_BASE)) uut (
    .clk              (clk),
    .rst_n            (rst_n),
    `AXIL_M_RD(ibus_axi, ib),
    `AXIL_M(dbus_axi, db),
    .cpu_irq          (cpu_irq),
    .cpu_irq_ack      (cpu_irq_ack),
    .cpu_irq_id       (cpu_irq_id),
    .cpu_in_trap      (cpu_in_trap)
);

// instruction memory (ibus, read-only)
axi_lite_mem_model #(
    .WORDS(1024), .BASE(`IMEM_BASE), .INIT_FILE("program_axi.hex"),
    .READ_LAT(0), .SEED(11)
) imem_inst (
    .clk(clk), .rst_n(rst_n),
    .awaddr(32'b0), .awvalid(1'b0), .awready(),
    .wdata(32'b0), .wstrb(4'b0), .wvalid(1'b0), .wready(),
    .bresp(), .bvalid(), .bready(1'b0),
    .araddr(ib_araddr), .arvalid(ib_arvalid), .arready(ib_arready),
    .rdata(ib_rdata), .rresp(ib_rresp), .rvalid(ib_rvalid), .rready(ib_rready)
);

// dbus interconnect: peripheral window (PIC + mtimer), dmem is the default
axi_lite_dec2 #(
    .S1_BASE(`PERIP_BASE), .S1_MASK(`PERIP_MASK)
) dbus_dec_inst (
    .clk(clk), .rst_n(rst_n),
    `AXIL_M(m, db), `AXIL_M(s0, d0), `AXIL_M(s1, p)
);

// data memory (dbus default leg, with latency -> multi-cycle stalls)
axi_lite_mem_model #(
    .WORDS(1024), .BASE(`DMEM_BASE),
    .READ_LAT(1), .WRITE_LAT(1), .SEED(23)
) dmem_inst (
    .clk(clk), .rst_n(rst_n), `AXIL_BARE(d0)
);

// peripheral window split: mtimer, the PIC is the default
axi_lite_dec2 #(
    .S1_BASE(`TMR_BASE), .S1_MASK(`TMR_MASK)
) perip_dec_inst (
    .clk(clk), .rst_n(rst_n),
    `AXIL_M(m, p), `AXIL_M(s0, pp), `AXIL_M(s1, t)
);

// the device under second test: the real PIC on the decoded window.
// Channel 7 is the real mtimer interrupt; the TB plays channels 0..6.
pic pic_inst (
    .clk(clk), .rst_n(rst_n),
    .irq_src({tmr_irq, irq_src[6:0]}),
    .cpu_irq(cpu_irq), .cpu_irq_id(cpu_irq_id),
    .cpu_irq_ack(cpu_irq_ack), .cpu_in_trap(cpu_in_trap),
    `AXIL_M(s_axi, pp)
);

// the device under third test: the real mtimer (D26/D27)
mtimer mtimer_inst (
    .clk(clk), .rst_n(rst_n),
    .irq(tmr_irq),
    `AXIL_M(s_axi, t)
);

// protocol monitors on both CPU buses and on the PIC / mtimer slave ports
// (err counts must end at 0)
wire [15:0] ib_mon_err, db_mon_err, p_mon_err, t_mon_err;
wire [31:0] ib_mon_rd, db_mon_rd, db_mon_wr, p_mon_rd, p_mon_wr;
wire [31:0] t_mon_rd, t_mon_wr;

axi_lite_monitor #(.NAME("ibus"), .HAS_WRITE(0)) ibus_mon (
    .clk(clk), .rst_n(rst_n),
    .awaddr(32'b0), .awvalid(1'b0), .awready(1'b0),
    .wdata(32'b0), .wstrb(4'b0), .wvalid(1'b0), .wready(1'b0),
    .bresp(2'b0), .bvalid(1'b0), .bready(1'b0),
    .araddr(ib_araddr), .arvalid(ib_arvalid), .arready(ib_arready),
    .rdata(ib_rdata), .rresp(ib_rresp), .rvalid(ib_rvalid), .rready(ib_rready),
    .err_cnt(ib_mon_err), .rd_cnt(ib_mon_rd), .wr_cnt()
);

axi_lite_monitor #(.NAME("dbus"), .HAS_WRITE(1)) dbus_mon (
    .clk(clk), .rst_n(rst_n), `AXIL_BARE(db),
    .err_cnt(db_mon_err), .rd_cnt(db_mon_rd), .wr_cnt(db_mon_wr)
);

axi_lite_monitor #(.NAME("pic"), .HAS_WRITE(1)) pic_mon (
    .clk(clk), .rst_n(rst_n), `AXIL_BARE(pp),
    .err_cnt(p_mon_err), .rd_cnt(p_mon_rd), .wr_cnt(p_mon_wr)
);

axi_lite_monitor #(.NAME("tmr"), .HAS_WRITE(1)) tmr_mon (
    .clk(clk), .rst_n(rst_n), `AXIL_BARE(t),
    .err_cnt(t_mon_err), .rd_cnt(t_mon_rd), .wr_cnt(t_mon_wr)
);

// scoreboard slots: dmem word index = the program's byte offset / 4, named
// so the checks read by intent instead of a bare number
localparam
  W_SW          =   0/4, W_SB         =   4/4, W_SH          =   8/4,
  W_ILLEGAL     =  64/4, W_MAGIC      = 256/4, W_CSR_IMM     = 128/4,
  W_MSCRATCH    = 132/4, W_MIP        = 136/4, W_CPI         = 140/4,
  W_RAW         = 144/4, W_JALR_LINK  = 148/4, W_BTB_ALIAS   = 152/4,
  W_VEC_CAUSE   = 156/4, W_IRQ_LOAD   = 160/4, W_IRQ_ACTIVE  = 164/4,
  W_IRQ3_MEPC   = 168/4, W_X0         = 172/4, W_MHARTID     = 176/4,
  W_PIC_ENABLE  = 180/4, W_PIC_RAW    = 184/4, W_PIC_PEND    = 188/4,
  W_SYNC_COUNT  = 192/4, W_IRQ_COUNT  = 196/4, W_IRQ3_MCAUSE = 200/4,
  W_WFI_MEPC    = 204/4, W_WFI_FALL   = 208/4, W_RAS         = 212/4,
  W_AUIPC       = 216/4, W_BRANCHES   = 220/4, W_CSRRCI      = 224/4,
  W_FWD_BOTH    = 228/4, W_MTIME_DEL  = 232/4, W_HPM3        = 236/4,
  W_TRIGGER     = 248/4, W_HPM5       = 260/4, W_HPM6        = 264/4,
  W_HPM7        = 268/4, W_HPM4       = 272/4, W_MTIME_HI    = 276/4,
  W_MTVAL       = 244/4, W_MISA       = 252/4, W_MID         = 280/4;

integer errors;

task check;
    input [31:0] expected;
    input [31:0] got;
    input [255:0] test_name;
    begin
        if (expected === got)
            $display("PASS: %0s = 0x%08h", test_name, got);
        else begin
            $display("FAIL: %0s -> expected 0x%08h, got 0x%08h",
                     test_name, expected, got);
            errors = errors + 1;
        end
    end
endtask

// cycle-by-cycle invariants
reg        ack5_seen;      // masked channel must never be acknowledged
reg        ack_double;     // ack is a 1-cycle pulse
reg        ack_in_stall;   // never accept an irq mid data transaction
reg [7:0]  ack_prev;
integer    ack2_count, ack3_count;
integer    ack0_count, ack1_count, ack4_count, ack6_count, ack7_count;
reg        id_bad;         // cpu_irq_id must be the lowest pending channel
reg        suppress_fail;  // an in-service channel must stay out of cpu_irq
reg [3:0]  ack3_age;       // cycles since ack[3], to skip the update pipeline

always @(posedge clk or negedge rst_n) begin
    if (~rst_n) begin
        ack5_seen  <= 0;
        ack_double <= 0;
        ack_in_stall <= 0;
        ack_prev   <= 8'b0;
        ack2_count <= 0;
        ack3_count <= 0;
        ack0_count <= 0;
        ack1_count <= 0;
        ack4_count <= 0;
        ack6_count <= 0;
        ack7_count <= 0;
        id_bad     <= 0;
        suppress_fail <= 0;
        ack3_age   <= 4'd0;
    end else begin
        if (cpu_irq_ack[5])            ack5_seen  <= 1;
        if (|(cpu_irq_ack & ack_prev)) ack_double <= 1;
        if (|cpu_irq_ack && uut.lsu_inst.active) ack_in_stall <= 1;
        if (cpu_irq_ack[0])            ack0_count <= ack0_count + 1;
        if (cpu_irq_ack[1])            ack1_count <= ack1_count + 1;
        if (cpu_irq_ack[2])            ack2_count <= ack2_count + 1;
        if (cpu_irq_ack[3])            ack3_count <= ack3_count + 1;
        if (cpu_irq_ack[4])            ack4_count <= ack4_count + 1;
        if (cpu_irq_ack[6])            ack6_count <= ack6_count + 1;
        if (cpu_irq_ack[7])            ack7_count <= ack7_count + 1;
        ack_prev <= cpu_irq_ack;

        // the id must point at a set cpu_irq bit with nothing below it
        if (|cpu_irq && (cpu_irq[cpu_irq_id] !== 1'b1 ||
                         (cpu_irq & ((8'h01 << cpu_irq_id) - 8'h01)) != 8'b0))
            id_bad <= 1;

        // source 3 is held high through its handler; once the ack has had
        // time to propagate, cpu_irq[3] must be low until MRET
        if (cpu_irq_ack[3])
            ack3_age <= 4'd1;
        else if (!cpu_in_trap)
            ack3_age <= 4'd0;
        else if (ack3_age != 4'd0 && ack3_age != 4'd15)
            ack3_age <= ack3_age + 4'd1;
        if (ack3_age >= 4'd3 && cpu_in_trap && irq_src[3] && cpu_irq[3])
            suppress_fail <= 1;
    end
end

// WFI quietness (D23): while asleep, the ibus read counter must freeze; at
// most the one fetch already in flight when sleep began may complete. The entry
// snapshot is retaken per sleep, so both WFIs are measured independently;
// wfi_noisy latches any extra read.
reg        wfi_prev, wfi_seen, wfi_noisy;
integer    wfi_cycles;
reg [31:0] wfi_rd_entry;

always @(posedge clk or negedge rst_n) begin
    if (~rst_n) begin
        wfi_prev  <= 0;
        wfi_seen  <= 0;
        wfi_noisy <= 0;
        wfi_cycles <= 0;
        wfi_rd_entry <= 32'b0;
    end else begin
        wfi_prev <= uut.wfi_wait;
        if (uut.wfi_wait) begin
            wfi_seen   <= 1;
            wfi_cycles <= wfi_cycles + 1;
            if (!wfi_prev)
                wfi_rd_entry <= ib_mon_rd;
            else if (ib_mon_rd - wfi_rd_entry > 32'd1)
                wfi_noisy <= 1;
        end
    end
end

// peripheral model: drives the PIC source lines the way the DMA / DP-SRAM
// would: raise on an event, hold until "the handler clears the peripheral"
time t_rbeat2, t_ack2, t_ack2_first, t_ack3;

// one sweep step: the program writes the trigger slot, the TB raises the
// channel's source (held level) and drops it on the ack, like the DMA/DP-SRAM handshake
task sweep_channel;
    input integer ch;
    begin
        while (!(db_awvalid === 1'b1 && db_awready === 1'b1 &&
                 db_awaddr === (`DMEM_BASE + W_TRIGGER*4))) @(posedge clk);
        irq_src[ch] = 1'b1;
        while (cpu_irq_ack[ch] !== 1'b1) @(posedge clk);
        irq_src[ch] = 1'b0;
    end
endtask

initial begin
    irq_src      = 8'b0;
    t_rbeat2     = 0;
    t_ack2       = 0;
    t_ack2_first = 0;
    t_ack3       = 0;

    wait (rst_n === 1'b1);
    @(posedge clk);

    // src 5: pending from the start; PIC-enabled by the program but never
    // enabled in mie -> must never be taken
    irq_src[5] = 1'b1;

    // irq #1 + #2: ch2 and ch3 rise together once the program sets
    // mstatus.MIE; the PIC must serve ch2 first (lower channel wins)
    wait (uut.csr_file_inst.mstatus_mie_q === 1'b1);
    repeat (3) @(posedge clk);
    irq_src[2] = 1'b1;
    irq_src[3] = 1'b1;
    while (cpu_irq_ack[2] !== 1'b1) @(posedge clk);
    t_ack2_first = $time;
    if (cpu_in_trap !== 1'b1)
        $display("FAIL: cpu_in_trap not set on irq ack");
    irq_src[2] = 1'b0;                       // ch2 handler cleared its source

    // ch3 is taken right after ch2's MRET; its source stays high through the
    // handler so the in-service mask is what keeps it out of cpu_irq (the
    // suppress_fail invariant watches this window), then drops at MRET
    while (cpu_irq_ack[3] !== 1'b1) @(posedge clk);
    t_ack3 = $time;
    while (cpu_in_trap === 1'b1) @(posedge clk);
    irq_src[3] = 1'b0;

    // irq #3: raise ch2 while the magic load is in flight; the take
    // must wait for the response (interrupt held through the stall)
    while (!(db_arvalid === 1'b1 &&
             db_araddr === (`DMEM_BASE + W_MAGIC*4))) @(posedge clk);
    irq_src[2] = 1'b1;
    while (!(db_rvalid === 1'b1 && db_rready === 1'b1)) @(posedge clk);
    t_rbeat2 = $time;
    while (cpu_irq_ack[2] !== 1'b1) @(posedge clk);
    t_ack2 = $time;
    irq_src[2] = 1'b0;

    // channel sweep, one trigger store per channel
    sweep_channel(0);
    sweep_channel(1);
    sweep_channel(4);
    sweep_channel(6);
end

// main sequence
integer i, tmo;

initial begin
    errors = 0;

    // dmem starts zeroed + the magic word the stall-irq test loads
    for (i = 0; i < 1024; i = i + 1)
        dmem_inst.mem[i] = 32'b0;
    dmem_inst.mem[W_MAGIC] = 32'hCAFE0001;        // byte address 0x2100

    wait (rst_n === 1'b1);

    tmo = 0;
    while (uut.regfile_inst.regs[23] !== 32'h123 && tmo < 20000) begin
        @(posedge clk);
        tmo = tmo + 1;
    end
    repeat (5) @(posedge clk);

    if (tmo >= 20000) begin
        $display("FAIL: timeout - program never reached the end marker");
        errors = errors + 1;
    end

    // arithmetic / logic / forwarding: each value depends on the previous
    // one, so a broken S3->S2 forward shows up as a wrong result
    check(32'd10,        uut.regfile_inst.regs[1],  "x1  ADDI");
    check(32'd15,        uut.regfile_inst.regs[2],  "x2  ADDI fwd");
    check(32'd25,        uut.regfile_inst.regs[3],  "x3  ADD fwd");
    check(32'd15,        uut.regfile_inst.regs[4],  "x4  SUB");
    check(32'd240,       uut.regfile_inst.regs[5],  "x5  XORI");
    check(32'd250,       uut.regfile_inst.regs[6],  "x6  OR");
    check(32'd10,        uut.regfile_inst.regs[7],  "x7  AND");
    check(32'd160,       uut.regfile_inst.regs[8],  "x8  SLLI");
    check(32'd40,        uut.regfile_inst.regs[9],  "x9  SRLI");
    check(32'hFFFFFFE7,  uut.regfile_inst.regs[10], "x10 SRAI");
    check(32'd1,         uut.regfile_inst.regs[11], "x11 SLT");
    check(32'd0,         uut.regfile_inst.regs[12], "x12 SLTU");
    check(32'h12345000,  uut.regfile_inst.regs[13], "x13 LUI");
    check(32'd0,         uut.regfile_inst.regs[0],  "x0 stays zero");

    // byte-lane load/store
    check(32'h00002000,  uut.regfile_inst.regs[14], "x14 dmem base");
    check(32'h12345000,  uut.regfile_inst.regs[15], "x15 LW");
    check(32'd122,       uut.regfile_inst.regs[17], "x17 LBU");
    check(32'hFFFFFFFF,  uut.regfile_inst.regs[19], "x19 LH sign-ext");
    check(32'd65535,     uut.regfile_inst.regs[20], "x20 LHU");
    check(32'hFFFFFF80,  uut.regfile_inst.regs[21], "x21 LB sign-ext");
    check(32'h12345000,  dmem_inst.mem[W_SW],          "dmem[0] SW");
    check(32'h00007A80,  dmem_inst.mem[W_SB],          "dmem[1] SB lanes");
    check(32'hFFFF0000,  dmem_inst.mem[W_SH],          "dmem[2] SH lane");
    check(32'h12345000,  dmem_inst.mem[W_RAW],         "RAW store->load result");

    // branches, JAL/JALR
    check(32'd15,        uut.regfile_inst.regs[22], "x22 BNE loop");
    check(32'd1,         uut.regfile_inst.regs[24], "x24 BEQ not-taken");
    check(`ADDR_back,    uut.regfile_inst.regs[25], "x25 JAL link");
    check(32'd107,       uut.regfile_inst.regs[26], "x26 JAL/JALR round-trip");
    check(32'd18,        dmem_inst.mem[W_BTB_ALIAS],         "BTB aliasing sum");
    check(`ADDR_jl_skip, dmem_inst.mem[W_JALR_LINK],         "JALR rd==rs1 link");

    // CSRs + sync traps, exact counting: 15 handler entries and one bit
    // per cause in x29, so a missing/double/spurious trap cannot cancel out
    check(`ADDR_handler_sync, uut.regfile_inst.regs[27], "x27 mtvec readback");
    check(32'd511,       uut.regfile_inst.regs[29], "x29 all 9 sync causes seen");
    check(32'd17,        dmem_inst.mem[W_SYNC_COUNT],         "sync trap count exact");
    check(32'd0,         dmem_inst.mem[W_ILLEGAL],         "illegal store: no mem write");
    check(32'd21,        dmem_inst.mem[W_CSR_IMM],         "CSRRWI/CSRRSI old value");
    check(32'd31,        dmem_inst.mem[W_MSCRATCH],         "mscratch round-trip");
    check(32'd0,         dmem_inst.mem[W_X0],         "x0 write ignored");
    check(32'd0,         dmem_inst.mem[W_MHARTID],         "mhartid reads HART_ID (0)");
    check(32'h00008000,  dmem_inst.mem[W_MTVAL],         "mtval = faulting load address");
    check(32'h40000100,  dmem_inst.mem[W_MISA],         "misa reads RV32I");
    check(32'd0,         dmem_inst.mem[W_MID],         "mvendorid/marchid/mimpid read 0");

    // interrupts through the real PIC: priority, suppression, masking and
    // the stall case, all observed at the CPU boundary (ack/mepc/mcause)
    check(32'h80000012,  dmem_inst.mem[W_IRQ3_MCAUSE],         "irq #3 mcause snapshot");
    check(32'h80000017,  uut.regfile_inst.regs[31], "x31 last irq mcause (timer)");
    check(32'h00200000,  dmem_inst.mem[W_MIP],         "mip shows masked ch5 only");
    check(32'd8,         dmem_inst.mem[W_IRQ_COUNT],         "irq handler entered 8x");
    check(32'd2,         ack2_count,                "exactly two ack[2] pulses");
    check(32'd1,         ack3_count,                "exactly one ack[3] pulse");
    check(32'd1,         ack0_count,                "sweep: one ack[0]");
    check(32'd1,         ack1_count,                "sweep: one ack[1]");
    check(32'd1,         ack4_count,                "sweep: one ack[4]");
    check(32'd1,         ack6_count,                "sweep: one ack[6]");
    check(32'd1,         ack7_count,                "timer: one ack[7]");
    check(32'd0,         {31'b0, ack5_seen},        "masked ch5 never acked");
    check(32'd0,         {31'b0, ack_double},       "ack is a 1-cycle pulse");
    check(32'd0,         {31'b0, ack_in_stall},     "no ack during a data stall");
    check(32'd0,         {31'b0, id_bad},           "cpu_irq_id = lowest pending");
    check(32'd0,         {31'b0, suppress_fail},    "in-service ch3 suppressed");
    if (t_ack2_first != 0 && t_ack3 > t_ack2_first)
        $display("PASS: ch2 served before ch3 (ack2 @%0t, ack3 @%0t)",
                 t_ack2_first, t_ack3);
    else begin
        $display("FAIL: PIC priority order (ack2 @%0t, ack3 @%0t)",
                 t_ack2_first, t_ack3);
        errors = errors + 1;
    end
    check(32'hCAFE0001,  dmem_inst.mem[W_IRQ_LOAD],         "load retired before irq #3");
    check(`ADDR_irq2_victim, dmem_inst.mem[W_IRQ3_MEPC],     "irq #3 mepc = boundary instr");

    // WFI + mtimer (D23/D26): the timer wakes the sleep through the PIC, mepc
    // lands past the WFI, and a mie-enabled MIE=0 wake falls through with no
    // handler entry (the entry count above stays exact)
    check(`ADDR_after_wfi, dmem_inst.mem[W_WFI_MEPC],       "WFI preempted: mepc = wfi+4");
    check(32'h00000077,  dmem_inst.mem[W_WFI_FALL],         "WFI falls through when MIE=0");
    if (wfi_seen && wfi_cycles >= 20 && !wfi_noisy)
        $display("PASS: WFI slept %0d cycles, <=1 ibus read per sleep", wfi_cycles);
    else begin
        $display("FAIL: WFI quietness (seen %0d, cycles %0d, noisy %0d)",
                 wfi_seen, wfi_cycles, wfi_noisy);
        errors = errors + 1;
    end

    // RAS (D24) + coverage fills: results are prediction-independent
    check(32'h00000243,  dmem_inst.mem[W_RAS],         "RAS calls/returns correct");
    check(`ADDR_auipc_spot, dmem_inst.mem[W_AUIPC],      "AUIPC");
    check(32'd15,        dmem_inst.mem[W_BRANCHES],         "BLT/BGE/BLTU/BGEU both ways");
    check(32'd26,        dmem_inst.mem[W_CSRRCI],         "CSRRCI");
    check(32'd42,        dmem_inst.mem[W_FWD_BOTH],         "add, both operands forwarded");

    // mtimer software write path (D26): MTIME_HI reads back what was written
    check(32'h000002AB,  dmem_inst.mem[W_MTIME_HI],         "mtimer MTIME_HI write/read");

    // hpm counters (D25) + mtime: exact where architectural, nonzero where the
    // value is latency-dependent. Trap count = 17 direct + 1 vectored + 8 irq.
    check(32'd26,        dmem_inst.mem[W_HPM6],         "mhpm6 counts every trap entry");
    if (dmem_inst.mem[W_MTIME_DEL] > 0 && dmem_inst.mem[W_HPM3] > 0 && dmem_inst.mem[W_HPM5] > 0 &&
        dmem_inst.mem[W_HPM7] > 0 && dmem_inst.mem[W_HPM4] > 0)
        $display("PASS: perf counters alive (mtimeD %0d, mispred %0d, dstall %0d, wfi %0d, fwait %0d)",
                 dmem_inst.mem[W_MTIME_DEL], dmem_inst.mem[W_HPM3], dmem_inst.mem[W_HPM5],
                 dmem_inst.mem[W_HPM7], dmem_inst.mem[W_HPM4]);
    else begin
        $display("FAIL: a perf counter stayed 0 (mtimeD %0d, mispred %0d, dstall %0d, wfi %0d, fwait %0d)",
                 dmem_inst.mem[W_MTIME_DEL], dmem_inst.mem[W_HPM3], dmem_inst.mem[W_HPM5],
                 dmem_inst.mem[W_HPM7], dmem_inst.mem[W_HPM4]);
        errors = errors + 1;
    end
    if (t_rbeat2 != 0 && t_ack2 > t_rbeat2)
        $display("PASS: irq #3 held through the AXI stall (R @%0t, ack @%0t)",
                 t_rbeat2, t_ack2);
    else begin
        $display("FAIL: irq #3 ordering (R @%0t, ack @%0t)", t_rbeat2, t_ack2);
        errors = errors + 1;
    end

    // PIC software interface, read back by the program over real AXI
    // transactions (IRQ_ACTIVE is read from inside the irq handler itself)
    check(32'h0000002C,  dmem_inst.mem[W_PIC_ENABLE],         "PIC IRQ_ENABLE readback");
    check(32'h00000020,  dmem_inst.mem[W_PIC_RAW],         "PIC IRQ_RAW: src5 high");
    check(32'h00000020,  dmem_inst.mem[W_PIC_PEND],         "PIC IRQ_PENDING: ch5 only");
    check(32'h00000080,  dmem_inst.mem[W_IRQ_ACTIVE],         "IRQ_ACTIVE in handler (timer)");

    // vectored mtvec
    check(`ADDR_vec_base | 32'h1, uut.csr_file_inst.mtvec_q, "mtvec vectored");
    check(32'd11,        dmem_inst.mem[W_VEC_CAUSE],         "vectored exception -> BASE");
    check(`ADDR_after_wfi, uut.csr_file_inst.mepc_q, "final mepc = wfi+4 (timer irq)");
    check(32'h80000017,  uut.csr_file_inst.mcause_q,"final mcause = timer irq");
    check(32'd0,         {31'b0, uut.csr_file_inst.mstatus_mie_q}, "mstatus.MIE after CSRRC");
    check(32'd0,         {31'b0, cpu_in_trap},      "cpu_in_trap after MRET");

    // CPI evidence: only meaningful with an un-stalled instruction bus
    if (imem_inst.READ_LAT == 0 && imem_inst.STALL_PROB == 0) begin
        if (dmem_inst.mem[W_CPI] >= 32'd33 && dmem_inst.mem[W_CPI] <= 32'd44)
            $display("PASS: CPI window = %0d cycles for 33 instrs", dmem_inst.mem[W_CPI]);
        else begin
            $display("FAIL: CPI window = %0d cycles for 33 instrs", dmem_inst.mem[W_CPI]);
            errors = errors + 1;
        end
    end else
        $display("SKIP: CPI check (imem latency/backpressure active)");

    // protocol monitors
    check(32'd0,         {16'b0, ib_mon_err},       "ibus protocol clean");
    check(32'd0,         {16'b0, db_mon_err},       "dbus protocol clean");
    check(32'd0,         {16'b0, p_mon_err},        "PIC port protocol clean");
    check(32'd0,         {16'b0, t_mon_err},        "mtimer port protocol clean");
    if (ib_mon_rd > 0 && db_mon_rd > 0 && db_mon_wr > 0 &&
        p_mon_rd > 0 && p_mon_wr > 0 && t_mon_rd > 0 && t_mon_wr > 0)
        $display("PASS: traffic seen (ibus rd %0d, dbus rd %0d wr %0d, pic rd %0d wr %0d, tmr rd %0d wr %0d)",
                 ib_mon_rd, db_mon_rd, db_mon_wr, p_mon_rd, p_mon_wr,
                 t_mon_rd, t_mon_wr);
    else begin
        $display("FAIL: a bus saw no traffic");
        errors = errors + 1;
    end

    // performance counters sane
    if (uut.csr_file_inst.minstret_q > 0 &&
        uut.csr_file_inst.mcycle_q > uut.csr_file_inst.minstret_q)
        $display("PASS: counters (mcycle %0d > minstret %0d)",
                 uut.csr_file_inst.mcycle_q, uut.csr_file_inst.minstret_q);
    else begin
        $display("FAIL: counters (mcycle %0d, minstret %0d)",
                 uut.csr_file_inst.mcycle_q, uut.csr_file_inst.minstret_q);
        errors = errors + 1;
    end

    // end marker
    check(32'h00000123,  uut.regfile_inst.regs[23], "x23 end marker");

    if (errors == 0)
        $display("== ALL TESTS PASSED ==");
    else
        $display("== %0d TESTS FAILED ==", errors);
    $finish;
end

endmodule
