# One canonical compile, shared by sim.do and regress.do.
#
# COMPILE ORDER
# The four vlog calls below are ordered bottom-up by dependency, and so is the
# content of each filelist:
#
#   1. rtl.f        the design, levelled: leaves -> alu_top/mtimer/pic -> cpu_top
#   2. tb_cpu.f     the system-bench models, then tb_cpu_axi which uses them
#   3. arb2 + tb_dual_core   the dual-core bench (ModelSim only)
#   4. tb_block.f   the block-level benches, each of which instantiates one
#                   RTL block from step 1
#
# Verilog-2005 resolves module instances at elaboration, not at compile time,
# so this order is not strictly required by the tool. It is kept anyway: macro
# and `include visibility IS order-dependent, a missing module is reported at
# the level that needed it instead of as one unresolved instance at the top,
# and downstream tools (lint, synthesis, formal front-ends) do require
# definition before use. rtl.f carries the full reasoning.

vlib work
vmap work work

# 1. RTL, in dependency-level order
vlog -f rtl.f

# 2. system bench. +incdir+. lets tb_cpu_axi find program_axi_sym.vh, the
#    label addresses generated by asm.py
vlog +incdir+. -f tb_cpu.f

# 3. dual-core bench: ModelSim-only (the Verilator flow runs the single-core
#    bench). The arbiter is a leaf and must precede the bench that uses it.
vlog ../hdl/axi_lite_arb2.v
vlog +incdir+../hdl ../hdl/tb_dual_core.v

# 4. block-level benches: reset, read-only, register fields, trap causes
vlog -f tb_block.f
