// Generated by asm.py: label addresses for the testbench.
`define ADDR__start 32'h00000000
`define ADDR_h0_wait 32'h00000018
`define ADDR_h0_done 32'h00000028
`define ADDR_hart1 32'h0000002c
`define ADDR_h1_wait 32'h00000030
`define ADDR_h1_done 32'h00000048
