onerror {quit -code 1 -f}
vlib work
vmap work work

# 1. RTL, in dependency-level order
vlog -f rtl.f

# 2. system bench. +incdir+. lets tb_cpu_axi find program_axi_sym.vh, the
#    label addresses generated by asm.py
vlog +incdir+. -f tb_cpu.f

# 3. Dual-core bench and shared-memory arbiter.
vlog ../hdl/axi_lite_arb2.v
vlog +incdir+../hdl ../hdl/rv32i_tb_dual_core.v

# 4. block-level benches: reset, read-only, register fields, trap causes
vlog -f tb_block.f

vlog +incdir+. +incdir+../hdl ../hdl/rv32i_tb_isa.v

vlog +incdir+. +incdir+../hdl ../hdl/pic_tb_reference.v
