// Generated by asm.py: label addresses for the testbench.
`define ADDR__start 32'h00000000
`define ADDR_fill 32'h00000034
`define ADDR_halt 32'h000000b0
`define ADDR_race_sram 32'h000000b4
`define ADDR_race_again 32'h000000bc
`define ADDR_race_done 32'h000000dc
`define ADDR_race_one 32'h000000e0
`define ADDR_hammer_one 32'h00000110
`define ADDR_wait_one 32'h00000120
`define ADDR_race 32'h00000148
`define ADDR_hammer 32'h00000178
`define ADDR_race_end 32'h000001bc
`define ADDR_handler 32'h00000300
