// Generated by asm.py: label addresses for the testbench.
`define ADDR__start 32'h00000000
`define ADDR_fill 32'h00000044
`define ADDR_clear 32'h00000064
`define ADDR_wait_dma 32'h000000ac
`define ADDR_dma_end 32'h000000d4
`define ADDR_compare 32'h000000e8
`define ADDR_same 32'h000000f8
`define ADDR_halt 32'h00000120
`define ADDR_handler 32'h00000300
