// Generated by asm.py: label addresses for the testbench.
`define ADDR__start 32'h00000000
`define ADDR_slot_loop 32'h00000038
`define ADDR_wait_slot 32'h00000050
`define ADDR_halt 32'h0000007c
`define ADDR_irq_handler 32'h00000080
