// Generated by asm.py: label addresses for the testbench.
`define ADDR__start 32'h00000000
`define ADDR_fill_loop 32'h00000010
`define ADDR_wait_irq 32'h0000009c
`define ADDR_cmp_loop 32'h000000b4
`define ADDR_cmp_ok 32'h000000c4
`define ADDR_halt 32'h00000108
`define ADDR_irq_handler 32'h0000010c
