// Generated by asm.py: label addresses for the testbench.
`define ADDR__start 32'h00000000
`define ADDR_resume7 32'h00000064
`define ADDR_resume8 32'h00000074
`define ADDR_halt 32'h00000084
`define ADDR_handler 32'h00000400
`define ADDR_fetch_fault 32'h00000430
