// Generated by asm.py: label addresses for the testbench.
`define ADDR__start 32'h00000000
`define ADDR_fill_src 32'h00000010
`define ADDR_fill_guard 32'h00000034
`define ADDR_xfer_loop 32'h0000009c
`define ADDR_poll_done 32'h000000c8
`define ADDR_halt 32'h000000fc
