// Generated by asm.py: label addresses for the testbench.
`define ADDR__start 32'h00000000
`define ADDR_fill_src 32'h00000038
`define ADDR_fill_dst1 32'h0000005c
`define ADDR_fill_dst2 32'h00000074
`define ADDR_check_dst1 32'h000001f4
`define ADDR_skip_dst1 32'h00000200
`define ADDR_check_dst2 32'h00000214
`define ADDR_skip_dst2 32'h00000220
`define ADDR_halt 32'h00000244
`define ADDR_run_ch0 32'h00000248
`define ADDR_poll 32'h0000027c
`define ADDR_poll_loop 32'h00000280
`define ADDR_poll_done 32'h000002a4
`define ADDR_release_ch0 32'h000002a8
`define ADDR_compare 32'h000002b8
`define ADDR_compare_loop 32'h000002c0
`define ADDR_compare_same 32'h000002d0
