// Generated by asm.py: label addresses for the testbench.
`define ADDR__start 32'h00000000
`define ADDR_wait_both 32'h0000004c
`define ADDR_halt 32'h00000078
`define ADDR_irq_handler 32'h0000007c
`define ADDR_outer 32'h00000090
`define ADDR_outer_spin 32'h000000c4
`define ADDR_inner 32'h000000e4
