// Generated by asm.py: label addresses for the testbench.
`define ADDR__start 32'h00000000
`define ADDR_config 32'h0000001c
`define ADDR_wait 32'h0000006c
`define ADDR_halt 32'h00000090
`define ADDR_handler 32'h00000200
`define ADDR_unwind 32'h00000284
