// Generated by asm.py: label addresses for the testbench.
`define ADDR__start 32'h00000000
`define ADDR_esc_wait 32'h00000054
`define ADDR_wait_both 32'h0000007c
`define ADDR_halt 32'h00000094
`define ADDR_irq_handler 32'h00000098
