// Generated by asm.py: label addresses for the testbench.
`define ADDR__start 32'h00000000
`define ADDR_fill_loop 32'h00000010
`define ADDR_poll_done 32'h00000094
`define ADDR_settle 32'h000000a4
`define ADDR_wait_irq 32'h000000dc
`define ADDR_cmp_loop 32'h000000f8
`define ADDR_cmp_ok 32'h00000108
`define ADDR_halt 32'h00000128
`define ADDR_irq_handler 32'h0000012c
