// Generated by asm.py: label addresses for the testbench.
`define ADDR__start 32'h00000000
`define ADDR_fill_good 32'h0000002c
`define ADDR_wait_good 32'h00000070
`define ADDR_good_done 32'h00000084
`define ADDR_cmp_good 32'h0000009c
`define ADDR_cmp_ok 32'h000000ac
`define ADDR_fill_bad 32'h000000d8
`define ADDR_wait_bad 32'h0000011c
`define ADDR_bad_done 32'h00000130
`define ADDR_halt 32'h00000158
