// Generated by asm.py: label addresses for the testbench.
`define ADDR__start 32'h00000000
`define ADDR_fill_loop 32'h00000024
`define ADDR_zero_loop 32'h00000040
`define ADDR_track_loop 32'h000000c8
`define ADDR_poll_word 32'h000000c8
`define ADDR_dmem_ok 32'h000000e4
`define ADDR_in_range 32'h000000f4
`define ADDR_tracking_done 32'h000000f8
`define ADDR_cmp_loop 32'h00000108
`define ADDR_cmp_ok 32'h00000118
`define ADDR_halt 32'h00000160
`define ADDR_trap_handler 32'h00000164
`define ADDR_is_interrupt 32'h00000180
`define ADDR_irq_dma 32'h0000019c
