// Generated by asm.py: label addresses for the testbench.
`define ADDR__start 32'h00000000
`define ADDR_fill_loop 32'h00000024
`define ADDR_zero_loop 32'h00000040
`define ADDR_phase_a_loop 32'h000000e4
`define ADDR_poll_burst 32'h000000e4
`define ADDR_burst_arrived 32'h00000118
`define ADDR_phase_a_range 32'h00000128
`define ADDR_phase_b_loop 32'h00000144
`define ADDR_phase_b_ok 32'h00000158
`define ADDR_cmp_loop 32'h0000016c
`define ADDR_cmp_ok 32'h0000017c
`define ADDR_halt 32'h000001c8
`define ADDR_trap_handler 32'h000001cc
`define ADDR_is_interrupt 32'h000001e8
`define ADDR_irq_dma 32'h00000204
