// Generated by asm.py: label addresses for the testbench.
`define ADDR__start 32'h00000000
`define ADDR_fill_ch 32'h00000014
`define ADDR_fill_word 32'h00000030
`define ADDR_desc_ch 32'h00000054
`define ADDR_wait_all 32'h000000ec
`define ADDR_cmp_ch 32'h0000012c
`define ADDR_cmp_word 32'h00000144
`define ADDR_cmp_ok 32'h00000154
`define ADDR_halt 32'h00000188
